import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Loader2, Save, RotateCcw, CheckCircle2, AlertCircle } from "lucide-react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

// Sprint 3A — Editor com auto-save (debounce 2s) + reset.
// Mantém estado controlado local (currentValue) e sincroniza para o servidor
// quando o usuário para de digitar por 2 segundos. Mostra estado:
// dirty (não salvo) → saving (request em voo) → saved (200 ok).
type SaveState = "idle" | "dirty" | "saving" | "saved" | "error";

interface CodeEditorProps {
  runId: string;
  artifactId: string;
  initialContent: string;
  language: string;
  isEdited: boolean;
  // Server tells us "this is the original generated by the agent"
  originalContent: string | null;
  // Disabled when run is in a state that shouldn't accept edits (deployed/cancelled).
  readOnly?: boolean;
}

export default function CodeEditor({
  runId,
  artifactId,
  initialContent,
  language,
  isEdited,
  originalContent,
  readOnly = false,
}: CodeEditorProps) {
  const { toast } = useToast();
  const [value, setValue] = useState(initialContent);
  const [state, setState] = useState<SaveState>("idle");
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Quando o servidor envia novo initialContent (ex.: refetch após reset/auto-fix),
  // sincronizamos. Mas só se NÃO estamos com mudanças locais não salvas — caso
  // contrário, sobrescreveríamos digitação do usuário.
  const lastSyncedRef = useRef(initialContent);
  useEffect(() => {
    if (initialContent !== lastSyncedRef.current && state !== "dirty" && state !== "saving") {
      setValue(initialContent);
      lastSyncedRef.current = initialContent;
      setState("idle");
    }
  }, [initialContent, state]);

  // Serialização de saves: garante que o último valor digitado sempre é
  // submetido após a request em voo terminar. Evita o problema clássico do
  // onSuccess marcar como "salvo" um payload anterior usando o `value` atual
  // (closure stale) e perder edições subsequentes.
  const inFlightRef = useRef<string | null>(null);
  const queuedRef = useRef<string | null>(null);

  const flushQueue = () => {
    if (queuedRef.current !== null && inFlightRef.current === null) {
      const next = queuedRef.current;
      queuedRef.current = null;
      saveMutation.mutate(next);
    }
  };

  const saveMutation = useMutation({
    mutationFn: async (content: string) => {
      inFlightRef.current = content;
      const res = await apiRequest("PATCH", `/api/ide/runs/${runId}/files/${artifactId}`, { content });
      return res.json();
    },
    onMutate: () => {
      setState("saving");
    },
    onSuccess: (_data, variables) => {
      // `variables` é exatamente o conteúdo enviado nesta request — nunca o
      // estado atual (que pode ter avançado). Marca esse payload como sincronizado.
      lastSyncedRef.current = variables as string;
      inFlightRef.current = null;
      // Se houver fila com versão mais nova, dispara imediatamente
      if (queuedRef.current !== null) {
        flushQueue();
      } else {
        setState("saved");
        setTimeout(() => setState((s) => (s === "saved" ? "idle" : s)), 1500);
      }
      queryClient.invalidateQueries({ queryKey: ["/api/ide/runs", runId] });
    },
    onError: (err: any) => {
      inFlightRef.current = null;
      setState("error");
      toast({
        title: "Erro ao salvar",
        description: err?.message || "Não foi possível salvar o arquivo",
        variant: "destructive",
      });
    },
  });

  // Submit serializado: se há request em voo, enfileira; senão dispara.
  const scheduleSave = (content: string) => {
    if (inFlightRef.current !== null) {
      queuedRef.current = content;
    } else {
      saveMutation.mutate(content);
    }
  };

  const resetMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", `/api/ide/runs/${runId}/files/${artifactId}/reset`);
      return res.json();
    },
    onSuccess: (data: any) => {
      setValue(data.content);
      lastSyncedRef.current = data.content;
      setState("idle");
      queryClient.invalidateQueries({ queryKey: ["/api/ide/runs", runId] });
      toast({ title: "Arquivo restaurado", description: "Conteúdo original do agente foi restaurado." });
    },
    onError: (err: any) => {
      toast({
        title: "Erro ao restaurar",
        description: err?.message || "Não foi possível restaurar",
        variant: "destructive",
      });
    },
  });

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const next = e.target.value;
    setValue(next);
    setState("dirty");
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      // Não dispara se nada mudou em relação ao último sync (evita salva inútil)
      if (next === lastSyncedRef.current) {
        setState("idle");
        return;
      }
      scheduleSave(next);
    }, 2000);
  };

  // Salva imediato em ⌘/Ctrl+S
  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "s") {
      e.preventDefault();
      if (debounceRef.current) clearTimeout(debounceRef.current);
      if (value !== lastSyncedRef.current) scheduleSave(value);
    }
  };

  // Limpa debounce no unmount; flush se houver mudança pendente.
  useEffect(() => {
    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
        debounceRef.current = null;
      }
    };
  }, []);

  const showReset = isEdited || (originalContent !== null && value !== originalContent);

  return (
    <div className="flex flex-col gap-2 h-full" data-testid={`editor-artifact-${artifactId}`}>
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Badge variant="outline">{language}</Badge>
          {isEdited && (
            <Badge className="bg-amber-500/20 text-amber-700 dark:text-amber-300 border-amber-500/30" data-testid={`badge-edited-${artifactId}`}>
              ✏ editado
            </Badge>
          )}
          <SaveIndicator state={state} />
        </div>
        <div className="flex items-center gap-2">
          {showReset && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => resetMutation.mutate()}
              disabled={resetMutation.isPending || readOnly}
              data-testid={`button-reset-${artifactId}`}
              className="h-7 text-xs gap-1.5"
            >
              {resetMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : <RotateCcw className="h-3 w-3" />}
              Restaurar original
            </Button>
          )}
        </div>
      </div>
      <textarea
        data-testid={`textarea-code-${artifactId}`}
        value={value}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        readOnly={readOnly}
        spellCheck={false}
        className="flex-1 min-h-[300px] w-full resize-none font-mono text-xs leading-relaxed bg-muted text-foreground p-3 rounded-md border focus:outline-none focus:ring-1 focus:ring-ring whitespace-pre"
      />
    </div>
  );
}

function SaveIndicator({ state }: { state: SaveState }) {
  if (state === "idle") return null;
  if (state === "dirty") {
    return (
      <span className="flex items-center gap-1 text-[11px] text-muted-foreground" data-testid="save-indicator-dirty">
        <Save className="h-3 w-3" /> não salvo
      </span>
    );
  }
  if (state === "saving") {
    return (
      <span className="flex items-center gap-1 text-[11px] text-blue-600" data-testid="save-indicator-saving">
        <Loader2 className="h-3 w-3 animate-spin" /> salvando…
      </span>
    );
  }
  if (state === "saved") {
    return (
      <span className="flex items-center gap-1 text-[11px] text-emerald-600" data-testid="save-indicator-saved">
        <CheckCircle2 className="h-3 w-3" /> salvo
      </span>
    );
  }
  return (
    <span className="flex items-center gap-1 text-[11px] text-destructive" data-testid="save-indicator-error">
      <AlertCircle className="h-3 w-3" /> erro
    </span>
  );
}
